site_name: CyberSecurity Writeups
site_url: https://https://lincoln5702.github.io/
nav:
  - About Me: about_me.md
  - Notes: 
    - PrivilegeEscalation: 
         - notes/privilegeescalation/Abusing_vulnerable_software.md
         - notes/privilegeescalation/Abusing_dangerous_privileges.md
         - notes/privilegeescalation/Windows Privilege Escalation.md
         - notes/privilegeescalation/Linux Privilege escalation.md
         - notes/privilegeescalation/Tools_for_winprivesc.md
         - notes/privilegeescalation/Abusing service misconfigurations.md 
    - Web Hacking:
        - notes/WebHacking/recon.md
        - notes/WebHacking/methodology.md
        - notes/WebHacking/SQL lab.md
    - tools:
        - notes/tools/Nmap.md    

    - Others:
        - Important note.md 
  - Writeups:
     - Tryhackme:
         - tryhackme/Gaming Server CTF.md 
         - tryhackme/Root me.md
         - tryhackme/simple ctf.md
         - tryhackme/Overlayfs.md
         - tryhackme/lazyadmin.md
         - tryhackme/bountyhacker.md   
         - tryhackme/Blog.md 
         - tryhackme/IDE.md
         - tryhackme/relevant.md
         - tryhackme/overpass.md   
     - HacktheBox:
         - hackthebox/busqueda.md
  - CollegeResources:
    - MajorProject:
         - majorproject/apache kafka.md 
         - majorproject/openHIE.md
         
    
 
theme:
  name: material
  font: roboto
  features:
    - navigation.instant
    - navitaion.top
    - navigation.path
    - navigation.indexes
    - navigation.top
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.footer
    # - navigation.path
    #- toc.follow
    #- toc.integrate
    #- navigation.side
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en

  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


  # palette:
  #   - scheme: default
  #     toggle:
  #       icon: material/toggle-switch-off-outline
  #       name: Switch to dark mode
  #     primary: teal
  #     accent: purple
  #   - scheme: slate
  #     toggle:
  #       icon: material/toggle-switch
  #       name: Switch to light mode
  #     primary: teal
  #     accent: lime

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
  
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - stylesheets/extra.css
extra:

  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/lincoln5702
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/lincoln-basnet-010426206/



