site_name: CyberSecurity Writeups
site_url: https://https://lincoln5702.github.io/
nav:
  - About Me: about_me.md
  - Notes: 
    - PrivilegeEscalation:
      - WindowsPrivEsc: 
         - Abusing_vulnerable_software.md
         - Abusing_dangerous_privileges.md
         - Privilege escalation/Windows Privilege Escalation.md
    - Tools For Privesc:
      - Windows: 
         - Tools_for_winprivesc.md
    - Reconnaissance:
        - recon.md  
    - Web Hacking:
        - SQL lab.md 
        - methodology.md
    - Others:
        - Important note.md 
  - Writeups:
     - Hack The Box:
         - busqueda.md       
  - CollegeResources:
    - MajorProject:
         - apache kafka.md 
         
    
 
theme:
  name: material
  font: roboto
  features:
    - navigation.instant
    - navitaion.top
    - navigation.path
    - navigation.indexes
    - navigation.top
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    # - navigation.path
    #- toc.follow
    #- toc.integrate
    #- navigation.side
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  # palette:
  #   - scheme: default
  #     toggle:
  #       icon: material/toggle-switch-off-outline
  #       name: Switch to dark mode
  #     primary: teal
  #     accent: purple
  #   - scheme: slate
  #     toggle:
  #       icon: material/toggle-switch
  #       name: Switch to light mode
  #     primary: teal
  #     accent: lime

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
  
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - stylesheets/extra.css
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/lincoln5702
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/lincoln-basnet-010426206/

