site_name: CyberSecurity Writeups
site_url: https://https://lincoln5702.github.io/
nav:
 - Introduction: index.md
 - PrivilegeEscalation: 
    - WindowsPrivEsc:
       - Abusing_dangerous_privileges.md
       - Abusing_vulnerable_software.md
 - Tools For Privesc: 
     - Windows: Tools_for_winprivesc.md    
theme:
    name: material
    features:
      - navigation.instant
      - navitaion.top
      # - navigation.tabs
      # - navigation.sections
      # - navigation.path
      # - toc.follow
      # - toc.integrate
      # - navigation.side
      # - search.suggest
      # - search.highlight
      - content.tabs.link
      - content.code.annotation
      - content.code.copy
    language: en
    palette:
      - scheme: default
        toggle:
          icon: material/toggle-switch-off-outline
          name: Switch to dark mode
        primary: teal
        accent:  purple
      - scheme: slate
        toggle:
          icon: material/toggle-switch
          name: Switch to light mode
        primary: teal
        accent: lime
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  

